# H2 Database configuration for testing
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

# Disable mail configuration for testing
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=

# Disable AWS configuration for testing
spring.cloud.aws.s3.region=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566
cloud.aws.credentials.secret-key=test
cloud.aws.credentials.access-key=test

# Disable Firebase for testing
app.firebase-configuration-file=
