services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=adapteds-db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    expose:
      - 3306
